[tool.poetry]
name = "marvin2"
version = "0.1.0"
description = ""
authors = ["Kiritee Mishra <konark@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
openai = "^1.34.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
